# Generated by Django 4.2.11 on 2024-05-04 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Link <built-in function id>', max_length=100, verbose_name='Name of the link')),
                ('original_url', models.URLField(max_length=255, verbose_name='Original link: ')),
                ('short_url', models.URLField(max_length=255, verbose_name='Shortened link: ')),
                ('clicks_qty', models.IntegerField(default=0, verbose_name='Amount of clicks: ')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IP address of the device')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User-agent')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.links')),
            ],
        ),
    ]
