# Generated by Django 4.2.11 on 2024-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_links_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clicks',
            options={'verbose_name': 'Клик', 'verbose_name_plural': 'Клики'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='clicks',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата перехода: '),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='ip_address',
            field=models.CharField(max_length=100, verbose_name='IP адрес устройства: '),
        ),
        migrations.AlterField(
            model_name='clicks',
            name='user_agent',
            field=models.CharField(max_length=255, verbose_name='User-Agent: '),
        ),
        migrations.AlterField(
            model_name='links',
            name='clicks_qty',
            field=models.IntegerField(default=0, verbose_name='Количество кликов: '),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания: '),
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(default='Link <built-in function id>', max_length=100, verbose_name='Имя ссылки: '),
        ),
        migrations.AlterField(
            model_name='links',
            name='original_url',
            field=models.URLField(max_length=255, verbose_name='Оригинальная ссылка: '),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(max_length=255, verbose_name='Сокращенная ссылка: '),
        ),
    ]
